Add missing require
**Why**:
Because I got this error when I deployed:

```
NoMethodError: undefined method `to_json' for #<Hash:0x007fd504082470>
Did you mean?  to_s
```